# Generated by Django 4.2.6 on 2023-10-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FindSimilarInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='english', max_length=128)),
                ('count', models.PositiveIntegerField(default=5)),
                ('remove_stopwords', models.BooleanField(default=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_find_similar_inputs', to='django_find_similar.text')),
                ('texts', models.ManyToManyField(to='django_find_similar.text')),
            ],
        ),
    ]
