# Generated by Django 4.2.6 on 2023-11-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('language', models.CharField(default='english', max_length=128)),
                ('remove_stopwords', models.BooleanField(default=True)),
                ('cos', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('text', 'language', 'remove_stopwords')},
            },
        ),
        migrations.CreateModel(
            name='CheckResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('cos', models.FloatField(default=0.0)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_find_similar.checkresult')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_find_similar.texttoken')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='checkresult',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_find_similar.texttoken'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('token_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_find_similar.texttoken')),
            ],
            options={
                'abstract': False,
                'unique_together': {('value', 'token_text')},
            },
        ),
    ]
