# Generated by Django 4.2.6 on 2023-10-29 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_find_similar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('language', models.CharField(default='english', max_length=128)),
                ('remove_stopwords', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('token_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_find_similar.texttoken')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FindSimilarInput',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
