# Generated by Django 4.2.6 on 2023-10-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_find_similar', '0002_texttoken_token_delete_findsimilarinput_delete_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttoken',
            name='cos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
