# Generated by Django 4.2.6 on 2023-11-04 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_find_similar', '0003_texttoken_cos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_find_similar.texttoken')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('cos', models.FloatField(default=0.0)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_find_similar.checkresult')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_find_similar.texttoken')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
